@startuml "catalog-error"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:CatalogError" {
    @context : "https://w3id.org/dspace/2025/1/context.jsonld"
    @type : "dspace:CatalogError"
    dspace:code : String
    dspace:reason : Array
}

@enduml