name: Check Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited, synchronize, reopened]

jobs:
  trigger-workflow:
    uses: eclipse-dataspace-protocol-base/.github/.github/workflows/scan-pr-title.yml@main